JOB_CARD_SELECTOR = "//div[@class='jobsearch-LeftPane']/div[@id='mosaic-jobResults']/div/ul/li/div[@class[contains( . , 'cardOutline')]]"
JOB_ID_SELECTOR = ".//table//td[@class='resultContent']//a[@id]/@data-jk"
JOB_URL_SELECTOR = ".//table//td[@class='resultContent']//a[@id]/@href"
JOB_TITLE_SELECTOR = ".//table//td[@class='resultContent']//a[@id]/span/@title"
JOB_SALARY_SELECTOR = ".//div[@class='metadata salary-snippet-container']//text()"
COMPANY_NAME_SELECTOR = ".//span[@class='companyName']/text()"
COMPANY_LOCATION_SELECTOR = ".//div[@class='companyLocation']/text()"
COMPANY_RATING_SELECTOR = ".//span[@class='ratingNumber']/span/text()"
JOB_SHIFT_SELECTOR = ".//div[@class='metadata']/div[svg[@aria-label='Shift']]/text()"
JOB_TYPE_SELECTOR = ".//div[@class='metadata']/div[svg[@aria-label='Job type']]/text()"
JOB_DETAIL_JSON_SELECTOR = "//script[@type='application/ld+json']/text()"
JOB_METADATA_JSON_SELECTOR = "//script[contains(text(), 'window._initialData')]/text()"
